#!/usr/bin/env bash
set -euo pipefail

_FRP_INSTALL_CLIENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -f "${_FRP_INSTALL_CLIENT_DIR}/lib/frp-common.sh" ]] || {
  echo "ERROR: missing project file: ${_FRP_INSTALL_CLIENT_DIR}/lib/frp-common.sh" >&2
  exit 1
}
# shellcheck source=lib/frp-common.sh
. "${_FRP_INSTALL_CLIENT_DIR}/lib/frp-common.sh"
# shellcheck source=lib/frp-client-common.sh
. "${_FRP_INSTALL_CLIENT_DIR}/lib/frp-client-common.sh"

frp_valid_allocator_url() {
  local url="${1:-}"
  case "$url" in
    http://?*)
      return 1
      ;;
    https://?*) ;;
    *) return 1 ;;
  esac
  if [[ "$url" == *$'\n'* || "$url" == *$'\r'* || "$url" == *$'\t'* || "$url" == *' '* ]]; then
    return 1
  fi
  local rest="${url#*://}"
  local hostport="${rest%%/*}"
  [[ -n "$hostport" ]]
}

frp_require_allocator_url() {
  local url="${FRP_ALLOCATOR_URL:-}"
  if [[ -z "$url" ]]; then
    echo "ERROR: FRP allocator URL is not configured." >&2
    echo "Set FRP_ALLOCATOR_URL or use the installer command generated by frp-create-client." >&2
    exit 1
  fi
  if [[ "$url" == http://* ]]; then
    echo "ERROR: plain HTTP allocator URL is not supported; HTTPS is required." >&2
    exit 1
  fi
  if ! frp_valid_allocator_url "$url"; then
    echo "ERROR: FRP allocator URL is invalid; an https:// URL with a host is required." >&2
    exit 1
  fi
  ALLOCATOR_URL="$url"
}

menu_add_service() {
  local payload=""
  frp_ux_prompt_new_service payload
  if [[ -z "$payload" ]]; then
    return 0
  fi
  if ! services_add_json "$payload"; then
    return 0
  fi
}

menu_remove_service() {
  local choice
  if [[ "$(services_count)" == "0" ]]; then
    echo "ERROR: no services to remove" >&2
    return 0
  fi
  echo
  echo "Configured services"
  echo "==================="
  echo
  services_list
  echo "Remove from this install list only."
  echo "Nothing has been published yet, so no public port is reserved."
  echo
  choice="$(read_tty "Remove service number: " "")"
  if ! services_remove_index "$choice"; then
    return 0
  fi
}

collect_services_interactive() {
  local choice payload
  while true; do
    echo
    if [[ "$(services_count)" == "0" ]]; then
      frp_ux_empty_services_help
      echo "1) Add service"
      echo "2) Remove a service"
      echo "3) Install and connect"
      echo "4) Cancel"
      echo
      choice="$(read_tty "Select an option [1]: " "1")"
    else
      echo "Configured services"
      echo "==================="
      echo
      services_list
      frp_ux_configured_services_help
      echo "1) Add another service"
      echo "2) Remove a service"
      echo "3) Install and connect"
      echo "4) Cancel"
      echo
      choice="$(read_tty "Select: " "")"
    fi
    case "$choice" in
      1) menu_add_service ;;
      2) menu_remove_service ;;
      3)
        if [[ "$(services_count)" == "0" ]]; then
          echo "ERROR: at least one service must be configured" >&2
          continue
        fi
        frp_ux_print_install_summary "$SERVICES_FILE" "$FRP_VERSION"
        if frp_confirm_yes "Continue? [Y/n]: "; then
          return 0
        fi
        echo "Returning to the service configuration menu."
        ;;
      4)
        echo "Cancelled."
        return 1
        ;;
      *) echo "ERROR: select 1-4" >&2 ;;
    esac
  done
}

collect_services() {
  services_init
  if [[ -n "${FRP_SERVICES_JSON:-}" ]]; then
    services_load_from_env
    if [[ "$(services_count)" == "0" ]]; then
      echo "ERROR: at least one service must be configured" >&2
      exit 1
    fi
    return 0
  fi
  collect_services_interactive || exit 1
}

print_complete() {
  local server="$1" services_json_file="$2"
  if frp_zero_touch_active || [[ "${FRP_ZERO_TOUCH_COMPLETE:-}" == "1" ]]; then
    python3 - "$server" "$services_json_file" <<'PY'
import json, sys
from pathlib import Path
server = sys.argv[1]
services = json.loads(Path(sys.argv[2]).read_text(encoding='utf-8'))
print()
print('FRP client setup complete.')
print()
if not services:
    print('Management identity enrolled (management-only mode).')
    print('No services are published and no public ports were allocated.')
    print('Add a service later with: sudo frp-client')
else:
    print('The requested remote service is connected.')
print('You can close this terminal.')
print()
for item in services:
    if item.get('enabled', True) is False:
        continue
    preset = item.get('preset') or 'custom'
    remote_port = item.get('remote_port')
    if preset == 'ssh':
        user = item.get('ssh_user') or 'root'
        print('SSH tunnel ready')
        print()
        print('Connect:')
        print('  ssh -p %s %s@%s' % (remote_port, user, server))
        print()
    elif preset == 'http':
        print('Connect:')
        print('  http://%s:%s' % (server, remote_port))
        print()
    elif preset == 'https':
        print('Connect:')
        print('  https://%s:%s' % (server, remote_port))
        print()
    else:
        print('Connect:')
        print('  %s:%s' % (server, remote_port))
        print()
PY
    return 0
  fi
  python3 - "$server" "$services_json_file" <<'PY'
import json,sys
from pathlib import Path
server = sys.argv[1]
services = json.loads(Path(sys.argv[2]).read_text(encoding='utf-8'))
print()
print('=========================================')
print(' FRP Installation Complete')
print('=========================================')
print()
print('Your FRP client is running successfully.')
print()
print('Published services')
print('------------------')
print()
for item in services:
    name = item.get('name') or item['id']
    preset = item.get('preset') or 'custom'
    remote_port = item.get('remote_port')
    print(name)
    print(f"  Local target : {item.get('local_ip')}:{item.get('local_port')}")
    print(f"  Public port  : {remote_port}")
    print()
    if preset == 'ssh':
        user = item.get('ssh_user') or 'root'
        print('Connect from another machine with:')
        print()
        print(f'  ssh -p {remote_port} {user}@{server}')
    elif preset == 'http':
        print('Access:')
        print()
        print(f'  http://{server}:{remote_port}')
    elif preset == 'https':
        print('Access:')
        print()
        print(f'  https://{server}:{remote_port}')
    else:
        print('Connect:')
        print()
        print(f'  {server}:{remote_port}')
    print()
print('For normal operation, this is the only command you need to remember:')
print()
print('  sudo frpctl')
print()
print('Then type help inside the CLI.')
print()
print('Useful commands')
print('---------------')
print()
print('Everyday CLI / status / update:')
print('  sudo frpctl')
print('  sudo frpctl status')
print('  sudo frpctl update')
print()
print('Advanced direct commands (still supported):')
print('  sudo frp-client')
print('  sudo frp-client status')
print('  sudo frp-client info')
print()
print('Systemd service:')
print('  sudo systemctl status frpc --no-pager')
print()
print('=========================================')
PY
}

frp_client_existing_install_message() {
  if frp_zero_touch_active; then
    echo "This client is already installed." >&2
    echo "Use sudo frpctl update or sudo frp-client manage." >&2
    return 0
  fi
  echo "ERROR: this host already has an FRP client installed." >&2
  echo >&2
  echo "A software update must not re-enroll the client and does not" >&2
  echo "require an Enrollment Code." >&2
  echo >&2
  echo "Upgrade in place with:" >&2
  echo "  sudo frpctl update" >&2
  echo >&2
  echo "or, from the bootstrap bundle:" >&2
  echo "  curl -fsSL https://raw.githubusercontent.com/datarelay-labs/frp-auto-deploy/v2.1.0/dist/bootstrap-client.sh | sudo bash -s -- --upgrade" >&2
  echo >&2
  echo "Use sudo frp-client to change published services." >&2
  echo "An Enrollment Code is only for first install or trust recovery." >&2
}

frp_client_upgrade_from_this_tree() {
  local source="${FRP_CLIENT_UPDATE_SOURCE:-${_FRP_INSTALL_CLIENT_DIR}}"
  local check_only=0
  if [[ "${FRP_CLIENT_UPDATE_CHECK:-}" == "1" ]]; then
    check_only=1
  fi
  frp_client_apply_upgrade "$source" "$check_only"
}

frp_client_main() {
  if [[ ${EUID} -ne 0 && -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    echo "ERROR: run as root, e.g. curl ... | sudo env FRP_ALLOCATOR_URL=... bash" >&2
    exit 1
  fi

  if frp_client_has_existing_install; then
    frp_client_existing_install_message
    return 1
  fi
  if frp_client_has_partial_install; then
    echo "ERROR: a partial FRP client installation was found." >&2
    echo "Repair it with: sudo frpctl update" >&2
    echo "or uninstall locally and enroll again." >&2
    echo "Do not re-run first-install bootstrap on a partial client." >&2
    frp_emit_failure_class RECOVERY_REQUIRED
    return 1
  fi

  frp_require_allocator_url
  if frp_zero_touch_active; then
    frp_zero_touch_require_inputs || return 1
  fi
  frp_bootstrap_allocator_ca "$ALLOCATOR_URL" || return 1
  frp_detect_architecture || exit 1

  if [[ -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    frp_require_bash || exit 1
    frp_detect_platform
    frp_detect_package_manager
    frp_print_detected_linux
    echo
    frp_require_systemd || exit 1
    FRP_DEPENDENCY_ROLE=client
    if [[ "${FRP_INSTALL_HOOK_DEP_FAIL:-}" == "1" ]]; then
      echo "ERROR: simulated package manager failure" >&2
      frp_emit_failure_class DEPENDENCY_INSTALL_FAILED
      exit 1
    fi
    ensure_dependencies || {
      frp_emit_failure_class DEPENDENCY_INSTALL_FAILED
      exit 1
    }
    frp_require_python || exit 1
  fi

  SERVICES_FILE="$(mktemp)"
  ALLOCATED_FILE="$(mktemp)"
  ENROLL_META_FILE="$(mktemp)"
  TMPDIR="$(frp_secure_mktemp_dir)"
  chmod 600 "$SERVICES_FILE" "$ALLOCATED_FILE" "$ENROLL_META_FILE"
  trap 'rm -rf "$TMPDIR" "$SERVICES_FILE" "$ALLOCATED_FILE" "$ENROLL_META_FILE"; unset FRP_TOKEN ENROLL_SECRET FRP_ENROLLMENT_CODE TOKEN_CIPHERTEXT FRP_BOOTSTRAP_TICKET' EXIT

  if frp_zero_touch_active; then
    :
  else
    frp_ux_intro
    frp_ux_enrollment_help
    prompt_secret "Enrollment Code: " FRP_ENROLLMENT_CODE

    if [[ "$FRP_ENROLLMENT_CODE" != *.* ]]; then
      echo "ERROR: invalid enrollment code format" >&2
      exit 1
    fi
    ENROLL_ID="${FRP_ENROLLMENT_CODE%%.*}"
    ENROLL_SECRET="${FRP_ENROLLMENT_CODE#*.}"
    collect_services
  fi

  local etc_frp
  etc_frp="$(frp_client_path /etc/frp)"
  mkdir -p "$etc_frp"
  if [[ -n "${FRP_TEST_MACHINE_ID:-}" ]]; then
    MACHINE_ID="$FRP_TEST_MACHINE_ID"
  elif [[ -s /etc/machine-id ]]; then
    MACHINE_ID="$(tr -d '\n' </etc/machine-id)"
  elif [[ -s "${etc_frp}/client-id" ]]; then
    MACHINE_ID="$(tr -d '\n' <"${etc_frp}/client-id")"
  else
    MACHINE_ID="$(openssl rand -hex 16)"
    printf '%s\n' "$MACHINE_ID" >"${etc_frp}/client-id"
    chmod 600 "${etc_frp}/client-id"
  fi

  HOSTNAME_VALUE="$(frp_short_hostname)"

  if frp_zero_touch_active; then
    local ssh_user ssh_port
    ssh_user="${FRP_SSH_USER:-}"
    ssh_port="${FRP_SSH_PORT:-22}"
    if [[ -n "$ssh_user" ]]; then
      frp_zero_touch_ssh_preflight "$ssh_user" "$ssh_port" || return 1
    fi
  fi

  if ! frp_identity_ensure; then
    exit 1
  fi

  if frp_zero_touch_active; then
    echo "Completing one-time setup ..."
    if ! frp_redeem_bootstrap_ticket "$ALLOCATOR_URL" "$MACHINE_ID" "$HOSTNAME_VALUE" \
      "$SERVICES_FILE" ENROLL_ID ENROLL_SECRET; then
      return 1
    fi
    FRP_ZERO_TOUCH_COMPLETE=1
    FRP_SERVICES_JSON="$(python3 -c 'import json,sys; print(json.dumps(json.load(open(sys.argv[1],encoding="utf-8"))))' "$SERVICES_FILE")"
    export FRP_SERVICES_JSON
    services_load_from_env
    unset FRP_SERVICES_JSON
  fi

  echo "Validating enrollment and requesting persistent public ports ..."
  frp_enroll_services "$ALLOCATOR_URL" "$ENROLL_ID" "$ENROLL_SECRET" \
    "$MACHINE_ID" "$HOSTNAME_VALUE" "$SERVICES_FILE" "$ALLOCATED_FILE" "$ENROLL_META_FILE" \
    || exit 1
  FRP_SERVER="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8"))["frp_server"])' "$ENROLL_META_FILE")"
  FRP_SERVER_PORT="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8"))["frp_server_port"])' "$ENROLL_META_FILE")"
  FRP_TRANSPORT="$(python3 -c 'import json,sys; print((json.load(open(sys.argv[1],encoding="utf-8")).get("frp_transport") or "tcp"))' "$ENROLL_META_FILE")"
  TOKEN_CIPHERTEXT="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8"))["token_ciphertext"])' "$ENROLL_META_FILE")"
  merge_allocated_services
  FRP_TOKEN="$(frp_decrypt_token "$TOKEN_CIPHERTEXT" "$ENROLL_SECRET")" || exit 1

  if [[ -z "${FRP_ARCH:-}" ]]; then
    frp_detect_architecture || exit 1
  fi

  if [[ "${FRP_SKIP_DOWNLOAD:-}" != "1" ]]; then
    ARCHIVE="$TMPDIR/frp.tar.gz"
    URL="https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/frp_${FRP_VERSION}_linux_${FRP_ARCH}.tar.gz"
    echo "Downloading FRP ${FRP_VERSION} (${FRP_ARCH}) ..."
    if [[ "${FRP_INSTALL_HOOK_DOWNLOAD_FAIL:-}" == "1" ]]; then
      echo "ERROR: failed to download FRP archive" >&2
      frp_emit_failure_class DOWNLOAD_FAILED
      exit 1
    fi
    if ! curl -fL --retry 3 -o "$ARCHIVE" "$URL"; then
      echo "ERROR: failed to download FRP archive" >&2
      frp_emit_failure_class DOWNLOAD_FAILED
      exit 1
    fi
    echo "Verifying checksum ..."
    printf '%s  %s\n' "$EXPECTED_SHA" "$ARCHIVE" | sha256sum -c - || {
      frp_emit_failure_class INTEGRITY_FAILED
      exit 1
    }
    extracted="$(frp_extract_frp_member "$ARCHIVE" "$TMPDIR" frpc)" || {
      frp_emit_failure_class STAGING_FAILED
      exit 1
    }
    frp_validate_frp_binary "$extracted" "$FRP_VERSION" "$FRP_ARCH" || {
      frp_emit_failure_class INTEGRITY_FAILED
      exit 1
    }
    frp_atomic_install "$extracted" /usr/local/bin/frpc 0755 || {
      frp_emit_failure_class FILE_COMMIT_FAILED
      exit 1
    }
  fi

  HOST_SAFE="$(printf '%s' "$HOSTNAME_VALUE" | tr -cs 'A-Za-z0-9._-' '-')"
  HOST_ID="${HOST_SAFE}-${MACHINE_ID:0:8}"
  FRPC_TOML="$(frp_client_path /etc/frp/frpc.toml)"
  ACCESS_INFO="$(frp_client_path /etc/frp/access-info.txt)"
  mkdir -p "$(dirname "$FRPC_TOML")"
  echo "Validating configuration ..."
  render_frpc_toml "$FRPC_TOML" "$FRP_SERVER" "$FRP_SERVER_PORT" "$FRP_TOKEN" "$HOST_ID" "$SERVICES_FILE" "${FRP_TRANSPORT:-tcp}"
  frp_client_verify_config "$FRPC_TOML" || exit 1

  if [[ "$(services_count)" != "0" && "${FRP_SKIP_SYSTEMD:-}" != "1" && -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    echo "Installing systemd service ..."
    UNIT_SRC=""
    if [[ -f "${_FRP_INSTALL_CLIENT_DIR}/client/frpc.service" ]]; then
      UNIT_SRC="${_FRP_INSTALL_CLIENT_DIR}/client/frpc.service"
    fi
    if [[ -n "$UNIT_SRC" ]]; then
      install -m 0644 "$UNIT_SRC" /etc/systemd/system/frpc.service
    else
      cat >/etc/systemd/system/frpc.service <<'EOF2'
[Unit]
Description=FRP Client
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/frpc -c /etc/frp/frpc.toml
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF2
    fi
    echo "Starting FRP client ..."
    systemctl daemon-reload || {
      frp_emit_failure_class SYSTEMD_RELOAD_FAILED
      exit 1
    }
    if ! systemctl enable frpc >/dev/null; then
      echo "ERROR: systemd enable failed; installation is not complete." >&2
      frp_emit_failure_class SYSTEMD_ENABLE_FAILED
      exit 1
    fi
    if ! systemctl restart frpc; then
      echo "ERROR: frpc failed to start; local files were written and the server reservation is preserved." >&2
      frp_emit_failure_class SERVICE_START_FAILED
      exit 1
    fi

    echo "Verifying published proxies ..."
    mapfile -t PROXY_NAMES < <(proxy_names_from_services "$HOST_ID")
    if ! wait_for_proxies "${PROXY_NAMES[@]}"; then
      echo "ERROR: frpc did not register every requested proxy successfully" >&2
      journalctl -u frpc -n 80 --no-pager >&2 || true
      frp_emit_failure_class HEALTH_CHECK_FAILED
      exit 1
    fi
  elif [[ "$(services_count)" == "0" ]]; then
    echo "Management-only mode: frpc is not started until a service is enabled."
    if [[ "${FRP_SKIP_SYSTEMD:-}" != "1" && -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
      echo "Installing inactive systemd service for future services ..."
      if [[ -f "${_FRP_INSTALL_CLIENT_DIR}/client/frpc.service" ]]; then
        install -m 0644 "${_FRP_INSTALL_CLIENT_DIR}/client/frpc.service" /etc/systemd/system/frpc.service
      else
        cat >/etc/systemd/system/frpc.service <<'EOF2'
[Unit]
Description=FRP Client
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/frpc -c /etc/frp/frpc.toml
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF2
      fi
      systemctl daemon-reload || {
        frp_emit_failure_class SYSTEMD_RELOAD_FAILED
        exit 1
      }
    fi
  fi

  render_access_info "$ACCESS_INFO" "$FRP_SERVER" "$SERVICES_FILE"
  frp_write_client_state "$(frp_client_state_path)" "$ALLOCATOR_URL" "$FRP_SERVER" \
    "$FRP_SERVER_PORT" "$HOSTNAME_VALUE" "$MACHINE_ID" "$HOST_ID" "$SERVICES_FILE" \
    "${FRP_TRANSPORT:-tcp}"
  frp_state_has_secrets "$(frp_client_state_path)" || {
    echo "ERROR: client-state.json must not contain secrets" >&2
    exit 1
  }

  frp_client_install_management_files "${_FRP_INSTALL_CLIENT_DIR}"

  print_complete "$FRP_SERVER" "$SERVICES_FILE"
}

frp_client_installer_usage() {
  cat <<'EOF'
Usage: install-client.sh [--upgrade] [--source DIR] [--check]

  (default)   First-time client enrollment and FRP install
  --upgrade   Upgrade management tools on an existing client
  --source    Source tree for --upgrade (default: this installer tree)
  --check     With --upgrade, report versions without changing files

An already-installed client is not re-enrolled. Use --upgrade / frpctl update
for software updates. An Enrollment Code is not required for a software update.
EOF
}

if [[ "${FRP_CLIENT_SOURCED:-}" != "1" ]]; then
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --upgrade|upgrade)
        FRP_CLIENT_UPGRADE=1
        shift
        ;;
      --source)
        FRP_CLIENT_UPDATE_SOURCE="${2:-}"
        shift 2
        ;;
      --check|--dry-run)
        FRP_CLIENT_UPDATE_CHECK=1
        shift
        ;;
      -h|--help)
        frp_client_installer_usage
        exit 0
        ;;
      *)
        echo "ERROR: unknown option: $1" >&2
        frp_client_installer_usage >&2
        exit 2
        ;;
    esac
  done
  if [[ "${FRP_CLIENT_UPGRADE:-}" == "1" ]]; then
    frp_client_upgrade_from_this_tree
    exit $?
  fi
  frp_client_main
  exit $?
fi
