#!/usr/bin/env bash
set -euo pipefail

_FRP_INSTALL_CLIENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -f "${_FRP_INSTALL_CLIENT_DIR}/lib/frp-common.sh" ]] || {
  echo "ERROR: missing project file: ${_FRP_INSTALL_CLIENT_DIR}/lib/frp-common.sh" >&2
  exit 1
}
# shellcheck source=lib/frp-common.sh
. "${_FRP_INSTALL_CLIENT_DIR}/lib/frp-common.sh"
# shellcheck source=lib/frp-client-common.sh
. "${_FRP_INSTALL_CLIENT_DIR}/lib/frp-client-common.sh"

# When sourced (FRP_CLIENT_SOURCED=1), do not replace the caller EXIT trap and do
# not terminate the caller with `exit`. Temp cleanup uses a RETURN trap set from
# inside frp_client_main (not from a helper, which would fire when the helper returns).
frp_client_fail() {
  local rc="${1:-1}"
  if [[ "${FRP_CLIENT_SOURCED:-}" == "1" ]]; then
    frp_client_restore_shellopts
    return "$rc"
  fi
  exit "$rc"
}

frp_client_tmp_cleanup() {
  rm -rf "${TMPDIR:-}" "${SERVICES_FILE:-}" "${ALLOCATED_FILE:-}" "${ENROLL_META_FILE:-}" 2>/dev/null || true
  unset FRP_TOKEN ENROLL_SECRET FRP_ENROLLMENT_CODE TOKEN_CIPHERTEXT FRP_BOOTSTRAP_TICKET 2>/dev/null || true
  TMPDIR=""
  SERVICES_FILE=""
  ALLOCATED_FILE=""
  ENROLL_META_FILE=""
}

frp_client_begin_tmp() {
  SERVICES_FILE="$(mktemp)"
  ALLOCATED_FILE="$(mktemp)"
  ENROLL_META_FILE="$(mktemp)"
  TMPDIR="$(frp_secure_mktemp_dir)"
  chmod 600 "$SERVICES_FILE" "$ALLOCATED_FILE" "$ENROLL_META_FILE"
  FRP_CLIENT_TMP_OPEN=1
  if [[ "${FRP_CLIENT_SOURCED:-}" != "1" ]]; then
    # shellcheck disable=SC2064
    trap 'frp_client_tmp_cleanup' EXIT
  fi
}

frp_client_end_tmp() {
  if [[ "${FRP_CLIENT_TMP_OPEN:-}" != "1" ]]; then
    trap - RETURN 2>/dev/null || true
    return 0
  fi
  FRP_CLIENT_TMP_OPEN=0
  frp_client_tmp_cleanup
  if [[ "${FRP_CLIENT_SOURCED:-}" != "1" ]]; then
    trap - EXIT
  fi
  trap - RETURN 2>/dev/null || true
}

frp_client_restore_shellopts() {
  if [[ -n "${FRP_CLIENT_SAVED_SHELLOPTS:-}" ]]; then
    eval "${FRP_CLIENT_SAVED_SHELLOPTS}" || true
  fi
}


frp_valid_allocator_url() {
  frp_validate_https_url "${1:-}"
}

frp_require_allocator_url() {
  local url="${FRP_ALLOCATOR_URL:-}"
  if [[ -z "$url" ]]; then
    echo "ERROR: FRP allocator URL is not configured." >&2
    echo "Set FRP_ALLOCATOR_URL or use the installer command generated by frp-create-client." >&2
    frp_client_fail 1 || return 1
  fi
  if [[ "$url" == http://* ]]; then
    echo "ERROR: plain HTTP allocator URL is not supported; HTTPS is required." >&2
    frp_client_fail 1 || return 1
  fi
  if ! frp_valid_allocator_url "$url"; then
    echo "ERROR: FRP allocator URL is invalid; an https:// URL with a host is required." >&2
    frp_client_fail 1 || return 1
  fi
  ALLOCATOR_URL="$url"
}

menu_add_service() {
  local payload=""
  frp_ux_prompt_new_service payload
  if [[ -z "$payload" ]]; then
    return 0
  fi
  if ! services_add_json "$payload"; then
    return 0
  fi
}

menu_remove_service() {
  local choice
  if [[ "$(services_count)" == "0" ]]; then
    echo "ERROR: no services to remove" >&2
    return 0
  fi
  echo
  echo "Configured services"
  echo "==================="
  echo
  services_list
  echo "Remove from this install list only."
  echo "Nothing has been published yet, so no public port is reserved."
  echo
  choice="$(read_tty "Remove service number: " "")"
  if ! services_remove_index "$choice"; then
    return 0
  fi
}

collect_services_interactive() {
  local choice payload
  while true; do
    echo
    if [[ "$(services_count)" == "0" ]]; then
      frp_ux_empty_services_help
      echo "1) Add service"
      echo "2) Remove a service"
      echo "3) Install and connect"
      echo "4) Cancel"
      echo
      choice="$(read_tty "Select an option [1]: " "1")"
    else
      echo "Configured services"
      echo "==================="
      echo
      services_list
      frp_ux_configured_services_help
      echo "1) Add another service"
      echo "2) Remove a service"
      echo "3) Install and connect"
      echo "4) Cancel"
      echo
      choice="$(read_tty "Select: " "")"
    fi
    case "$choice" in
      1) menu_add_service ;;
      2) menu_remove_service ;;
      3)
        if [[ "$(services_count)" == "0" ]]; then
          echo "ERROR: at least one service must be configured" >&2
          continue
        fi
        frp_ux_print_install_summary "$SERVICES_FILE" "$FRP_VERSION"
        if frp_confirm_yes "Continue? [Y/n]: "; then
          return 0
        fi
        echo "Returning to the service configuration menu."
        ;;
      4)
        echo "Cancelled."
        return 1
        ;;
      *) echo "ERROR: select 1-4" >&2 ;;
    esac
  done
}

collect_services() {
  services_init
  if [[ -n "${FRP_SERVICES_JSON:-}" ]]; then
    services_load_from_env
    if [[ "$(services_count)" == "0" ]]; then
      echo "ERROR: at least one service must be configured" >&2
      exit 1
    fi
    return 0
  fi
  collect_services_interactive || exit 1
}

print_complete() {
  local server="$1" services_json_file="$2"
  if frp_zero_touch_active || [[ "${FRP_ZERO_TOUCH_COMPLETE:-}" == "1" ]]; then
    python3 - "$server" "$services_json_file" <<'PY'
import json, sys
from pathlib import Path
server = sys.argv[1]
services = json.loads(Path(sys.argv[2]).read_text(encoding='utf-8'))
print()
print('FRP client setup complete.')
print()
if not services:
    print('Management identity enrolled (management-only mode).')
    print('No services are published and no public ports were allocated.')
    print('Add a service later with: sudo frp-client')
else:
    print('The requested remote service is connected.')
print('You can close this terminal.')
print()
for item in services:
    if item.get('enabled', True) is False:
        continue
    preset = item.get('preset') or 'custom'
    remote_port = item.get('remote_port')
    if preset == 'ssh':
        user = item.get('ssh_user')
        print('SSH tunnel ready')
        print()
        if user:
            print('Connect:')
            print('  ssh -p %s %s@%s' % (remote_port, user, server))
        else:
            print('SSH user: legacy / unspecified')
        print()
    elif preset == 'http':
        print('Connect:')
        print('  http://%s:%s' % (server, remote_port))
        print()
    elif preset == 'https':
        print('Connect:')
        print('  https://%s:%s' % (server, remote_port))
        print()
    else:
        print('Connect:')
        print('  %s:%s' % (server, remote_port))
        print()
PY
    return 0
  fi
  local service_hint='Systemd service:
  sudo systemctl status frpc --no-pager'
  if frp_is_darwin; then
    service_hint="launchd daemon:
  sudo launchctl print system/${FRP_MACOS_LAUNCHD_LABEL}"
  fi
  FRP_SERVICE_HINT="$service_hint" python3 - "$server" "$services_json_file" <<'PY'
import json,os,sys
from pathlib import Path
server = sys.argv[1]
services = json.loads(Path(sys.argv[2]).read_text(encoding='utf-8'))
print()
print('=========================================')
print(' FRP Installation Complete')
print('=========================================')
print()
print('Your FRP client is running successfully.')
print()
print('Published services')
print('------------------')
print()
for item in services:
    name = item.get('name') or item['id']
    preset = item.get('preset') or 'custom'
    remote_port = item.get('remote_port')
    print(name)
    print(f"  Local target : {item.get('local_ip')}:{item.get('local_port')}")
    print(f"  Public port  : {remote_port}")
    print()
    if preset == 'ssh':
        user = item.get('ssh_user')
        if user:
            print('Connect from another machine with:')
            print()
            print(f'  ssh -p {remote_port} {user}@{server}')
        else:
            print('SSH user: legacy / unspecified')
    elif preset == 'http':
        print('Access:')
        print()
        print(f'  http://{server}:{remote_port}')
    elif preset == 'https':
        print('Access:')
        print()
        print(f'  https://{server}:{remote_port}')
    else:
        print('Connect:')
        print()
        print(f'  {server}:{remote_port}')
    print()
print('For normal operation, this is the only command you need to remember:')
print()
print('  sudo frpctl')
print()
print('Then type help inside the CLI.')
print()
print('Useful commands')
print('---------------')
print()
print('Everyday CLI / status / update:')
print('  sudo frpctl')
print('  sudo frpctl status')
print('  sudo frpctl update')
print()
print('Advanced direct commands (still supported):')
print('  sudo frp-client')
print('  sudo frp-client status')
print('  sudo frp-client info')
print()
print(os.environ.get('FRP_SERVICE_HINT', ''))
print()
print('=========================================')
PY
}

frp_client_existing_install_message() {
  if frp_zero_touch_active; then
    echo "This client is already installed." >&2
    echo "Use sudo frpctl update or sudo frp-client manage." >&2
    return 0
  fi
  echo "ERROR: this host already has an FRP client installed." >&2
  echo >&2
  echo "A software update must not re-enroll the client and does not" >&2
  echo "require an Enrollment Code." >&2
  echo >&2
  echo "Upgrade in place with:" >&2
  echo "  sudo frpctl update" >&2
  # Optional bootstrap URL: only when release identity resolves to a real ref.
  # candidate → exact 40-char SHA; dev → main; stable → vX.Y.Z.
  # Never hardcode a nonexistent stable tag for pre-release / candidate installs.
  local bootstrap_ref=""
  if bootstrap_ref="$(frp_release_git_ref 2>/dev/null)" && [[ -n "$bootstrap_ref" ]]; then
    local channel
    channel="$(frp_release_channel 2>/dev/null || true)"
    if [[ "$channel" == "candidate" ]] && ! frp_is_exact_commit_sha "$bootstrap_ref"; then
      bootstrap_ref=""
    fi
  fi
  if [[ -n "$bootstrap_ref" ]]; then
    echo >&2
    echo "or, from the bootstrap bundle:" >&2
    echo "  curl -fsSL https://raw.githubusercontent.com/${FRP_GITHUB_OWNER}/${FRP_GITHUB_REPO}/${bootstrap_ref}/dist/bootstrap-client.sh | sudo bash -s -- --upgrade" >&2
  fi
  echo >&2
  echo "Use sudo frp-client to change published services." >&2
  echo "An Enrollment Code is only for first install or trust recovery." >&2
}

# Write the platform service definition (systemd unit or launchd plist) without
# enabling or starting it.
frp_client_install_service_definition() {
  local unit_src="" unit_tmp
  if frp_is_darwin; then
    frp_macos_launchd_install || return 1
    return 0
  fi
  if [[ -f "${_FRP_INSTALL_CLIENT_DIR}/client/frpc.service" ]]; then
    unit_src="${_FRP_INSTALL_CLIENT_DIR}/client/frpc.service"
  fi
  if [[ -n "$unit_src" ]]; then
    frp_write_compatible_systemd_unit "$unit_src" /etc/systemd/system/frpc.service
    return 0
  fi
  unit_tmp="$(mktemp)"
  cat >"$unit_tmp" <<'EOF2'
[Unit]
Description=FRP Client
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/frpc -c /etc/frp/frpc.toml
Restart=always
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF2
  frp_write_compatible_systemd_unit "$unit_tmp" /etc/systemd/system/frpc.service
  rm -f "$unit_tmp"
}

# Reload the service manager after writing a definition. launchd has no
# daemon-reload equivalent; loading the plist is the reload.
frp_client_service_daemon_reload() {
  if frp_is_darwin; then
    return 0
  fi
  systemctl daemon-reload
}

# Enable at boot and (re)start now.
frp_client_service_enable_and_start() {
  if frp_is_darwin; then
    # RunAtLoad in the plist is the launchd equivalent of `systemctl enable`;
    # a bootout/bootstrap cycle is the equivalent of `systemctl restart`.
    frp_macos_launchd_bootout
    if ! frp_macos_launchd_bootstrap; then
      frp_emit_failure_class SERVICE_START_FAILED
      return 1
    fi
    sleep 1
    if ! frp_macos_launchd_running; then
      echo "ERROR: frpc failed to start under launchd; local files were written and the server reservation is preserved." >&2
      frp_emit_failure_class SERVICE_START_FAILED
      return 1
    fi
    return 0
  fi
  if ! systemctl enable frpc >/dev/null; then
    echo "ERROR: systemd enable failed; installation is not complete." >&2
    frp_emit_failure_class SYSTEMD_ENABLE_FAILED
    return 1
  fi
  if ! systemctl restart frpc; then
    echo "ERROR: frpc failed to start; local files were written and the server reservation is preserved." >&2
    frp_emit_failure_class SERVICE_START_FAILED
    return 1
  fi
  return 0
}

frp_client_upgrade_from_this_tree() {
  local source="${FRP_CLIENT_UPDATE_SOURCE:-${_FRP_INSTALL_CLIENT_DIR}}"
  local check_only=0
  local kind="bundle"
  if [[ "${FRP_CLIENT_UPDATE_CHECK:-}" == "1" ]]; then
    check_only=1
  fi
  if [[ -n "${FRP_CLIENT_UPDATE_SOURCE:-}" ]]; then
    kind="source"
  fi
  _FRP_CLIENT_UPDATE_KIND="$kind" frp_client_apply_upgrade "$source" "$check_only"
}

frp_client_main() {
  # Sourced harnesses call us under `set +e` to capture status. Internal
  # `set -e` must not leak back and abort the caller on our non-zero return.
  # Not `local`: frp_client_fail / RETURN trap must observe this value.
  FRP_CLIENT_SAVED_SHELLOPTS=""
  if [[ "${FRP_CLIENT_SOURCED:-}" == "1" ]]; then
    FRP_CLIENT_SAVED_SHELLOPTS="$(set +o)"
  fi

  if [[ ${EUID} -ne 0 && -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    echo "ERROR: run as root, e.g. curl ... | sudo env FRP_ALLOCATOR_URL=... bash" >&2
    frp_client_fail 1 || return 1
  fi

  local recovering=0
  # Allow zero-touch resume when only a recovery journal (and maybe identity) exists.
  # Full installs (client-state.json) still refuse re-enrollment.
  if [[ -f "$(frp_client_state_path)" ]]; then
    frp_client_existing_install_message
    frp_client_restore_shellopts; return 1
  fi
  if frp_zero_touch_active && frp_recovery_journal_present; then
    recovering=1
  fi
  if [[ "$recovering" -eq 0 ]] && frp_client_has_existing_install; then
    frp_client_existing_install_message
    frp_client_restore_shellopts; return 1
  fi
  if [[ "$recovering" -eq 0 ]] && frp_client_has_partial_install; then
    echo "ERROR: a partial FRP client installation was found." >&2
    echo "Repair it with: sudo frpctl update" >&2
    echo "or uninstall locally and enroll again." >&2
    echo "Do not re-run first-install bootstrap on a partial client." >&2
    frp_emit_failure_class RECOVERY_REQUIRED
    frp_client_restore_shellopts; return 1
  fi

  frp_require_allocator_url || return 1
  if frp_zero_touch_active; then
    if [[ "$recovering" -eq 1 ]]; then
      # Resume path: ticket already consumed; do not require a second bootstrap ticket.
      :
    else
      frp_zero_touch_require_inputs || return 1
    fi
  fi
  frp_bootstrap_allocator_ca "$ALLOCATOR_URL" || return 1
  frp_detect_os >/dev/null || frp_client_fail 1 || return 1
  frp_detect_architecture || frp_client_fail 1 || return 1

  if [[ -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    frp_require_bash || frp_client_fail 1 || return 1
    if frp_is_darwin; then
      frp_macos_require_supported_release || frp_client_fail 1 || return 1
      frp_macos_print_detected
      echo
      frp_require_service_manager || frp_client_fail 1 || return 1
      if [[ "${FRP_INSTALL_HOOK_DEP_FAIL:-}" == "1" ]]; then
        echo "ERROR: simulated dependency failure" >&2
        frp_emit_failure_class DEPENDENCY_INSTALL_FAILED
        frp_client_fail 1 || return 1
      fi
      # No apt/dnf/brew mutation on macOS: dependencies are required, not installed.
      frp_macos_require_dependencies || {
        frp_emit_failure_class DEPENDENCY_INSTALL_FAILED
        frp_client_fail 1 || return 1
      }
      frp_require_python || frp_client_fail 1 || return 1
      frp_macos_ensure_dirs || frp_client_fail 1 || return 1
    else
      frp_detect_platform
      frp_detect_package_manager
      frp_print_detected_linux
      echo
      frp_require_service_manager || frp_client_fail 1 || return 1
      FRP_DEPENDENCY_ROLE=client
      if [[ "${FRP_INSTALL_HOOK_DEP_FAIL:-}" == "1" ]]; then
        echo "ERROR: simulated package manager failure" >&2
        frp_emit_failure_class DEPENDENCY_INSTALL_FAILED
        frp_client_fail 1 || return 1
      fi
      ensure_dependencies || {
        frp_emit_failure_class DEPENDENCY_INSTALL_FAILED
        frp_client_fail 1 || return 1
      }
      frp_require_python || frp_client_fail 1 || return 1
    fi
  fi

  frp_client_begin_tmp
  if [[ "${FRP_CLIENT_SOURCED:-}" == "1" ]]; then
    trap 'frp_client_end_tmp; [[ -n "${FRP_CLIENT_SAVED_SHELLOPTS:-}" ]] && eval "${FRP_CLIENT_SAVED_SHELLOPTS}" || true; trap - RETURN' RETURN
  fi

  if frp_zero_touch_active; then
    :
  else
    frp_ux_intro
    frp_ux_enrollment_help
    prompt_secret "Enrollment Code: " FRP_ENROLLMENT_CODE

    if [[ "$FRP_ENROLLMENT_CODE" != *.* ]]; then
      echo "ERROR: invalid enrollment code format" >&2
      frp_client_fail 1 || return 1
    fi
    ENROLL_ID="${FRP_ENROLLMENT_CODE%%.*}"
    ENROLL_SECRET="${FRP_ENROLLMENT_CODE#*.}"
    collect_services
  fi

  local etc_frp
  etc_frp="$(frp_client_path /etc/frp)"
  mkdir -p "$etc_frp"
  if [[ -n "${FRP_TEST_MACHINE_ID:-}" ]]; then
    MACHINE_ID="$FRP_TEST_MACHINE_ID"
  elif frp_is_darwin; then
    # IOPlatformUUID survives renames and user changes; hostname stays mutable
    # metadata and is never folded into the identity.
    MACHINE_ID="$(frp_macos_machine_id)" || frp_client_fail 1 || return 1
  elif [[ -s /etc/machine-id ]]; then
    MACHINE_ID="$(tr -d '\n' </etc/machine-id)"
  elif [[ -s "${etc_frp}/client-id" ]]; then
    MACHINE_ID="$(tr -d '\n' <"${etc_frp}/client-id")"
  else
    MACHINE_ID="$(openssl rand -hex 16)"
    printf '%s\n' "$MACHINE_ID" >"${etc_frp}/client-id"
    chmod 600 "${etc_frp}/client-id"
  fi

  HOSTNAME_VALUE="$(frp_short_hostname)"

  if frp_zero_touch_active; then
    local ssh_user ssh_port
    ssh_user="${FRP_SSH_USER:-}"
    ssh_port="${FRP_SSH_PORT:-22}"
    if [[ -n "$ssh_user" ]]; then
      frp_zero_touch_ssh_preflight "$ssh_user" "$ssh_port" || return 1
    fi
  fi

  if ! frp_identity_ensure; then
    frp_client_fail 1 || return 1
  fi

  local resume_rc=1
  if frp_zero_touch_active; then
    echo "Completing one-time setup ..."
    set +e
    frp_recovery_journal_try_resume "$SERVICES_FILE" "$MACHINE_ID"
    resume_rc=$?
    set -e
    if [[ "$resume_rc" -eq 2 ]]; then
      return 1
    fi
    if [[ "$resume_rc" -eq 0 ]]; then
      echo "Resuming incomplete zero-touch enrollment (same identity and ports; ticket not re-redeemed) ..."
      FRP_ZERO_TOUCH_COMPLETE=1
      FRP_SERVICES_JSON="$(python3 -c 'import json,sys; print(json.dumps(json.load(open(sys.argv[1],encoding="utf-8"))))' "$SERVICES_FILE")"
      export FRP_SERVICES_JSON
      services_load_from_env
      unset FRP_SERVICES_JSON
      # Ticket was already consumed; drop it so it cannot be redeemed again by accident.
      unset FRP_BOOTSTRAP_TICKET
    else
      if ! frp_zero_touch_require_inputs; then
        return 1
      fi
      if ! frp_redeem_bootstrap_ticket "$ALLOCATOR_URL" "$MACHINE_ID" "$HOSTNAME_VALUE" \
        "$SERVICES_FILE" ENROLL_ID ENROLL_SECRET; then
        return 1
      fi
      FRP_ZERO_TOUCH_COMPLETE=1
      FRP_SERVICES_JSON="$(python3 -c 'import json,sys; print(json.dumps(json.load(open(sys.argv[1],encoding="utf-8"))))' "$SERVICES_FILE")"
      export FRP_SERVICES_JSON
      services_load_from_env
      unset FRP_SERVICES_JSON
      # Persist recovery journal before /enroll so a post-enroll crash can resume
      # without a second bootstrap ticket. Never stores the raw bootstrap ticket.
      if ! frp_recovery_journal_write "$ALLOCATOR_URL" "$MACHINE_ID" "$HOSTNAME_VALUE" \
        "$ENROLL_ID" "$ENROLL_SECRET" "$SERVICES_FILE" "${FRP_ALLOCATOR_CA_SHA256:-}"; then
        echo "ERROR: failed to write enroll recovery journal" >&2
        return 1
      fi
    fi
  fi

  echo "Validating enrollment and requesting persistent public ports ..."
  frp_enroll_services "$ALLOCATOR_URL" "$ENROLL_ID" "$ENROLL_SECRET" \
    "$MACHINE_ID" "$HOSTNAME_VALUE" "$SERVICES_FILE" "$ALLOCATED_FILE" "$ENROLL_META_FILE" \
    || frp_client_fail 1 || return 1
  FRP_SERVER="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8"))["frp_server"])' "$ENROLL_META_FILE")"
  FRP_SERVER_PORT="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8"))["frp_server_port"])' "$ENROLL_META_FILE")"
  FRP_TRANSPORT="$(python3 -c 'import json,sys; print((json.load(open(sys.argv[1],encoding="utf-8")).get("frp_transport") or "tcp"))' "$ENROLL_META_FILE")"
  TOKEN_CIPHERTEXT="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8"))["token_ciphertext"])' "$ENROLL_META_FILE")"
  merge_allocated_services
  FRP_TOKEN="$(frp_decrypt_token "$TOKEN_CIPHERTEXT" "$ENROLL_SECRET")" || frp_client_fail 1 || return 1

  # Crash-window simulation: after successful enroll, before durable client-state commit.
  if ! frp_client_test_hook FAIL_AFTER_ENROLL; then
    frp_emit_failure_class ENROLL_RECOVERY_PENDING
    return 1
  fi

  if [[ -z "${FRP_ARCH:-}" ]]; then
    frp_detect_architecture || frp_client_fail 1 || return 1
  fi

  if [[ "${FRP_SKIP_DOWNLOAD:-}" != "1" ]]; then
    ARCHIVE="$TMPDIR/frp.tar.gz"
    URL="$(frp_release_url "$FRP_VERSION" "$FRP_ARCH")" || frp_client_fail 1 || return 1
    echo "Downloading FRP ${FRP_VERSION} ($(frp_os)/${FRP_ARCH}) ..."
    if [[ "${FRP_INSTALL_HOOK_DOWNLOAD_FAIL:-}" == "1" ]]; then
      echo "ERROR: failed to download FRP archive" >&2
      frp_emit_failure_class DOWNLOAD_FAILED
      frp_client_fail 1 || return 1
    fi
    if ! curl -fL --retry 3 -o "$ARCHIVE" "$URL"; then
      echo "ERROR: failed to download FRP archive" >&2
      frp_emit_failure_class DOWNLOAD_FAILED
      frp_client_fail 1 || return 1
    fi
    echo "Verifying checksum ..."
    # macOS has shasum, not GNU sha256sum; both accept the same check format.
    if frp_is_darwin; then
      frp_macos_sha256_check "$EXPECTED_SHA" "$ARCHIVE" || {
        echo "ERROR: SHA256 checksum mismatch" >&2
        frp_emit_failure_class INTEGRITY_FAILED
        frp_client_fail 1 || return 1
      }
    else
      printf '%s  %s\n' "$EXPECTED_SHA" "$ARCHIVE" | sha256sum -c - || {
        frp_emit_failure_class INTEGRITY_FAILED
        frp_client_fail 1 || return 1
      }
    fi
    extracted="$(frp_extract_frp_member "$ARCHIVE" "$TMPDIR" frpc)" || {
      frp_emit_failure_class STAGING_FAILED
      frp_client_fail 1 || return 1
    }
    if frp_is_darwin && frp_command_exists xattr; then
      # curl does not set com.apple.quarantine, but a proxy or mirror might.
      xattr -d com.apple.quarantine "$extracted" 2>/dev/null || true
    fi
    # Mach-O binaries are not ELF, so the ELF arch probe reports non-elf and is
    # skipped; the pinned Apple Silicon SHA256 above is what constrains the arch.
    frp_validate_frp_binary "$extracted" "$FRP_VERSION" "$FRP_ARCH" || {
      frp_emit_failure_class INTEGRITY_FAILED
      frp_client_fail 1 || return 1
    }
    frp_atomic_install "$extracted" "$(frp_client_path /usr/local/bin/frpc)" 0755 || {
      frp_emit_failure_class FILE_COMMIT_FAILED
      frp_client_fail 1 || return 1
    }
  fi

  HOST_SAFE="$(printf '%s' "$HOSTNAME_VALUE" | tr -cs 'A-Za-z0-9._-' '-')"
  HOST_ID="${HOST_SAFE}-${MACHINE_ID:0:8}"
  FRPC_TOML="$(frp_client_path /etc/frp/frpc.toml)"
  ACCESS_INFO="$(frp_client_path /etc/frp/access-info.txt)"
  mkdir -p "$(dirname "$FRPC_TOML")"
  echo "Validating configuration ..."
  render_frpc_toml "$FRPC_TOML" "$FRP_SERVER" "$FRP_SERVER_PORT" "$FRP_TOKEN" "$HOST_ID" "$SERVICES_FILE" "${FRP_TRANSPORT:-tcp}" "$MACHINE_ID" "$(frp_client_identity_key_path)"
  frp_client_verify_config "$FRPC_TOML" || frp_client_fail 1 || return 1

  local service_label="systemd service"
  if frp_is_darwin; then
    service_label="launchd daemon"
  fi
  if [[ "$(services_count)" != "0" && "${FRP_SKIP_SYSTEMD:-}" != "1" && -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    echo "Installing ${service_label} ..."
    frp_client_install_service_definition || {
      frp_emit_failure_class FILE_COMMIT_FAILED
      frp_client_fail 1 || return 1
    }
    echo "Starting FRP client ..."
    frp_client_service_daemon_reload || {
      frp_emit_failure_class SYSTEMD_RELOAD_FAILED
      frp_client_fail 1 || return 1
    }
    frp_client_service_enable_and_start || frp_client_fail 1 || return 1

    echo "Verifying published proxies ..."
    # Read loop rather than mapfile: macOS ships bash 3.2 and the zero-touch
    # one-liner pipes this script straight into /bin/bash.
    PROXY_NAMES=()
    while IFS= read -r proxy_line; do
      [[ -n "$proxy_line" ]] || continue
      PROXY_NAMES+=("$proxy_line")
    done < <(proxy_names_from_services "$HOST_ID")
    if ! wait_for_proxies ${PROXY_NAMES[@]+"${PROXY_NAMES[@]}"}; then
      echo "ERROR: frpc did not register every requested proxy successfully" >&2
      frp_client_recent_service_logs 80 >&2 || true
      frp_emit_failure_class HEALTH_CHECK_FAILED
      frp_client_fail 1 || return 1
    fi
  elif [[ "$(services_count)" == "0" ]]; then
    echo "Management-only mode: frpc is not started until a service is enabled."
    if [[ "${FRP_SKIP_SYSTEMD:-}" != "1" && -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
      echo "Installing inactive ${service_label} for future services ..."
      frp_client_install_service_definition || {
        frp_emit_failure_class FILE_COMMIT_FAILED
        frp_client_fail 1 || return 1
      }
      frp_client_service_daemon_reload || {
        frp_emit_failure_class SYSTEMD_RELOAD_FAILED
        frp_client_fail 1 || return 1
      }
    fi
  fi

  # Simulate proxy health verification failure in isolated tests (post-enroll,
  # before durable client-state commit — matches HEALTH_CHECK_FAILED class).
  if ! frp_client_test_hook HEALTH_CHECK_FAIL; then
    frp_emit_failure_class HEALTH_CHECK_FAILED
    frp_client_fail 1 || return 1
  fi

  render_access_info "$ACCESS_INFO" "$FRP_SERVER" "$SERVICES_FILE"
  frp_write_client_state "$(frp_client_state_path)" "$ALLOCATOR_URL" "$FRP_SERVER" \
    "$FRP_SERVER_PORT" "$HOSTNAME_VALUE" "$MACHINE_ID" "$HOST_ID" "$SERVICES_FILE" \
    "${FRP_TRANSPORT:-tcp}"
  frp_apply_meta_clock_offset "$(frp_client_state_path)" "$ENROLL_META_FILE"
  frp_state_has_secrets "$(frp_client_state_path)" || {
    echo "ERROR: client-state.json must not contain secrets" >&2
    frp_client_fail 1 || return 1
  }
  # Durable normal state committed; recovery journal is no longer needed.
  frp_recovery_journal_delete || true

  frp_client_install_management_files "${_FRP_INSTALL_CLIENT_DIR}"

  print_complete "$FRP_SERVER" "$SERVICES_FILE"
  frp_client_end_tmp
}

frp_client_installer_usage() {
  cat <<'EOF'
Usage: install-client.sh [--upgrade] [--source DIR] [--check]

  (default)   First-time client enrollment and FRP install
  --upgrade   Upgrade management tools on an existing client
  --source    Source tree for --upgrade (default: this installer tree)
  --check     With --upgrade, report versions without changing files

An already-installed client is not re-enrolled. Use --upgrade / frpctl update
for software updates. An Enrollment Code is not required for a software update.
EOF
}

if [[ "${FRP_CLIENT_SOURCED:-}" != "1" ]]; then
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --upgrade|upgrade)
        FRP_CLIENT_UPGRADE=1
        shift
        ;;
      --source)
        FRP_CLIENT_UPDATE_SOURCE="${2:-}"
        shift 2
        ;;
      --check|--dry-run)
        FRP_CLIENT_UPDATE_CHECK=1
        shift
        ;;
      -h|--help)
        frp_client_installer_usage
        exit 0
        ;;
      *)
        echo "ERROR: unknown option: $1" >&2
        frp_client_installer_usage >&2
        exit 2
        ;;
    esac
  done
  if [[ "${FRP_CLIENT_UPGRADE:-}" == "1" ]]; then
    frp_client_upgrade_from_this_tree
    exit $?
  fi
  frp_client_main
  exit $?
fi
