#!/usr/bin/env bash
set -euo pipefail

PROJECT_VERSION="1.0.0"
FRP_VERSION="0.70.1"
FRP_SHA256_AMD64="333da23d1b9009d7c01638e9ba38cf4600f7d37d393f854e96ee1396adefa9a6"
FRP_SHA256_ARM64="3990f396a9a490ee7f0e5f355287750ed41520064ed999eab443b5e9a78d773d"

_FRP_INSTALL_CLIENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/frp-client-common.sh
. "${_FRP_INSTALL_CLIENT_DIR}/lib/frp-client-common.sh"

frp_valid_allocator_url() {
  local url="${1:-}"
  case "$url" in
    http://?*|https://?*) ;;
    *) return 1 ;;
  esac
  if [[ "$url" == *$'\n'* || "$url" == *$'\r'* || "$url" == *$'\t'* || "$url" == *' '* ]]; then
    return 1
  fi
  local rest="${url#*://}"
  local hostport="${rest%%/*}"
  [[ -n "$hostport" ]]
}

frp_require_allocator_url() {
  local url="${FRP_ALLOCATOR_URL:-}"
  if [[ -z "$url" ]]; then
    echo "ERROR: FRP allocator URL is not configured." >&2
    echo "Set FRP_ALLOCATOR_URL or use the installer command generated by frp-create-client." >&2
    exit 1
  fi
  if ! frp_valid_allocator_url "$url"; then
    echo "ERROR: FRP allocator URL is invalid; an http:// or https:// URL with a host is required." >&2
    exit 1
  fi
  ALLOCATOR_URL="$url"
}

frp_os_release_file() {
  printf '%s' "${FRP_OS_RELEASE_FILE:-/etc/os-release}"
}

frp_os_release_value() {
  local key="$1" file="$2" line value
  [[ -r "$file" ]] || return 0
  while IFS= read -r line || [[ -n "$line" ]]; do
    case "$line" in
      "${key}="*)
        value="${line#*=}"
        if [[ "$value" == \"*\" ]]; then
          value="${value#\"}"
          value="${value%\"}"
        elif [[ "$value" == \'*\' ]]; then
          value="${value#\'}"
          value="${value%\'}"
        fi
        printf '%s' "$value"
        return 0
        ;;
    esac
  done <"$file"
}

frp_detect_platform() {
  local file pretty name
  DISTRO_ID="unknown"
  DISTRO_NAME="Linux"
  DISTRO_VERSION=""
  file="$(frp_os_release_file)"
  if [[ -r "$file" ]]; then
    DISTRO_ID="$(frp_os_release_value ID "$file")"
    DISTRO_ID="${DISTRO_ID:-unknown}"
    pretty="$(frp_os_release_value PRETTY_NAME "$file")"
    name="$(frp_os_release_value NAME "$file")"
    DISTRO_NAME="${pretty:-${name:-Linux}}"
    DISTRO_VERSION="$(frp_os_release_value VERSION_ID "$file")"
  fi
}

frp_detect_architecture() {
  local machine
  machine="${FRP_TEST_UNAME_M:-$(uname -m)}"
  case "$machine" in
    x86_64)
      FRP_ARCH=amd64
      EXPECTED_SHA="$FRP_SHA256_AMD64"
      ;;
    aarch64|arm64)
      FRP_ARCH=arm64
      EXPECTED_SHA="$FRP_SHA256_ARM64"
      ;;
    *)
      echo "ERROR: unsupported architecture: ${machine}" >&2
      return 1
      ;;
  esac
}

frp_command_exists() {
  local cmd="$1"
  if [[ -n "${FRP_TEST_CMD_PATH:-}" ]]; then
    PATH="${FRP_TEST_CMD_PATH}" command -v "$cmd" >/dev/null 2>&1
  else
    command -v "$cmd" >/dev/null 2>&1
  fi
}

frp_package_manager_exists() {
  local cmd="$1"
  if [[ -n "${FRP_TEST_PM_PATH:-}" ]]; then
    PATH="${FRP_TEST_PM_PATH}" command -v "$cmd" >/dev/null 2>&1
  else
    command -v "$cmd" >/dev/null 2>&1
  fi
}

frp_package_manager_bin() {
  local cmd="$1"
  if [[ -n "${FRP_TEST_PM_PATH:-}" ]]; then
    PATH="${FRP_TEST_PM_PATH}" command -v "$cmd"
  else
    command -v "$cmd"
  fi
}

frp_detect_package_manager() {
  PACKAGE_MANAGER=""
  if frp_package_manager_exists dnf; then
    PACKAGE_MANAGER=dnf
  elif frp_package_manager_exists yum; then
    PACKAGE_MANAGER=yum
  elif frp_package_manager_exists apt-get; then
    PACKAGE_MANAGER=apt
  fi
}

frp_systemd_runtime_dir() {
  printf '%s' "${FRP_TEST_SYSTEMD_RUNTIME_DIR:-/run/systemd/system}"
}

frp_systemd_usable() {
  [[ -d "$(frp_systemd_runtime_dir)" ]]
}

frp_require_systemd() {
  if ! frp_command_exists systemctl; then
    echo "ERROR: this release requires a systemd-based Linux distribution." >&2
    return 1
  fi
  if ! frp_systemd_usable; then
    echo "ERROR: this release requires a systemd-based Linux distribution." >&2
    return 1
  fi
}

frp_print_detected_linux() {
  local pm="${PACKAGE_MANAGER:-none}"
  local init="unknown"
  if frp_command_exists systemctl && frp_systemd_usable; then
    init="systemd"
  fi
  echo "Detected Linux:"
  echo "  Distribution : ${DISTRO_NAME}"
  echo "  Package mgr  : ${pm}"
  echo "  Architecture : ${FRP_ARCH}"
  echo "  Init system  : ${init}"
}

frp_required_commands() {
  printf '%s\n' curl openssl python3 tar sha256sum timeout hostname install
}

frp_collect_missing_commands() {
  local cmd
  MISSING_COMMANDS=()
  while IFS= read -r cmd; do
    [[ -n "$cmd" ]] || continue
    if ! frp_command_exists "$cmd"; then
      MISSING_COMMANDS+=("$cmd")
    fi
  done < <(frp_required_commands)
}

frp_package_for_command() {
  local cmd="$1" pm="$2"
  case "$cmd" in
    curl) printf 'curl' ;;
    openssl) printf 'openssl' ;;
    python3) printf 'python3' ;;
    tar) printf 'tar' ;;
    sha256sum|timeout|install) printf 'coreutils' ;;
    hostname) printf 'hostname' ;;
    ss|ip)
      if [[ "$pm" == apt ]]; then
        printf 'iproute2'
      else
        printf 'iproute'
      fi
      ;;
    *)
      echo "ERROR: no package mapping for command: ${cmd}" >&2
      return 1
      ;;
  esac
}

frp_packages_for_missing() {
  local pm="$1" cmd pkg existing existing_pkg
  PACKAGES=(ca-certificates)
  for cmd in "${MISSING_COMMANDS[@]}"; do
    pkg="$(frp_package_for_command "$cmd" "$pm")"
    existing=0
    for existing_pkg in "${PACKAGES[@]}"; do
      if [[ "$existing_pkg" == "$pkg" ]]; then
        existing=1
        break
      fi
    done
    if (( existing == 0 )); then
      PACKAGES+=("$pkg")
    fi
  done
}

install_dependencies_apt() {
  local bin
  bin="$(frp_package_manager_bin apt-get)"
  export DEBIAN_FRONTEND=noninteractive
  "$bin" update
  "$bin" install -y --no-install-recommends "$@"
}

install_dependencies_dnf() {
  local bin
  bin="$(frp_package_manager_bin dnf)"
  "$bin" install -y "$@"
}

install_dependencies_yum() {
  local bin
  bin="$(frp_package_manager_bin yum)"
  "$bin" install -y "$@"
}

frp_print_missing_tools_error() {
  local cmd
  echo "ERROR: required tools are missing:" >&2
  for cmd in "${MISSING_COMMANDS[@]}"; do
    echo "  ${cmd}" >&2
  done
  echo >&2
  echo "Automatic dependency installation supports apt, dnf, and yum." >&2
  echo "Install the missing tools manually and run the installer again." >&2
}

ensure_dependencies() {
  frp_collect_missing_commands
  if ((${#MISSING_COMMANDS[@]} == 0)); then
    return 0
  fi
  if [[ -z "${PACKAGE_MANAGER:-}" ]]; then
    frp_detect_package_manager
  fi
  if [[ -z "${PACKAGE_MANAGER:-}" ]]; then
    frp_print_missing_tools_error
    return 1
  fi
  frp_packages_for_missing "$PACKAGE_MANAGER"
  case "$PACKAGE_MANAGER" in
    apt) install_dependencies_apt "${PACKAGES[@]}" ;;
    dnf) install_dependencies_dnf "${PACKAGES[@]}" ;;
    yum) install_dependencies_yum "${PACKAGES[@]}" ;;
    *)
      echo "ERROR: unsupported package manager: ${PACKAGE_MANAGER}" >&2
      return 1
      ;;
  esac
  frp_collect_missing_commands
  if ((${#MISSING_COMMANDS[@]} > 0)); then
    echo "ERROR: missing required command after dependency installation:" >&2
    local cmd
    for cmd in "${MISSING_COMMANDS[@]}"; do
      echo "  ${cmd}" >&2
    done
    return 1
  fi
}

prompt_secret() {
  local prompt="$1" var="$2"
  if [[ -n "${!var:-}" ]]; then return 0; fi
  if [[ -r /dev/tty ]]; then
    read -r -s -p "$prompt" "$var" </dev/tty
    echo >/dev/tty
  else
    echo "ERROR: no TTY and $var is not set" >&2
    exit 1
  fi
}

read_tty() {
  local prompt="$1" default="${2:-}"
  local value=""
  if [[ -r /dev/tty ]]; then
    read -r -p "$prompt" value </dev/tty || true
  else
    echo "ERROR: no TTY for interactive setup; set FRP_SERVICES_JSON" >&2
    exit 1
  fi
  printf '%s' "${value:-$default}"
}

infer_ssh_user() {
  local user="${FRP_SSH_USER:-${SUDO_USER:-root}}"
  if [[ "$user" == "root" && -n "${LOGNAME:-}" && "$LOGNAME" != root ]]; then
    user="$LOGNAME"
  fi
  printf '%s' "$user"
}

probe_tcp() {
  local host="$1" port="$2"
  timeout 3 bash -c "echo >/dev/tcp/${host}/${port}" >/dev/null 2>&1
}

maybe_warn_connectivity() {
  local host="$1" port="$2" label="$3"
  if [[ "${FRP_SKIP_CONNECTIVITY_CHECK:-}" == "1" ]]; then
    return 0
  fi
  if probe_tcp "$host" "$port"; then
    return 0
  fi
  echo "WARNING: cannot connect to ${label} ${host}:${port} (continuing; target may be remote or not yet listening)"
}

prompt_service_id() {
  local default="$1"
  local sid
  sid="$(read_tty "Service ID [${default}]: " "$default")"
  printf '%s' "$sid"
}

prompt_target_host() {
  local default="${1:-127.0.0.1}"
  read_tty "Target host [${default}]: " "$default"
}

prompt_target_port() {
  local default="$1"
  read_tty "Target port [${default}]: " "$default"
}

service_payload() {
  python3 - "$@" <<'PY'
import json, sys
preset = sys.argv[1]
sid = sys.argv[2]
name = sys.argv[3]
host = sys.argv[4]
port = sys.argv[5]
payload = {
  'id': sid,
  'name': name,
  'protocol': 'tcp',
  'local_ip': host,
  'local_port': port,
  'preset': preset,
}
if preset == 'ssh':
    payload['ssh_user'] = sys.argv[6] if len(sys.argv) > 6 else 'root'
print(json.dumps(payload))
PY
}

add_preset_ssh() {
  local sid host port user payload
  sid="$(prompt_service_id ssh)"
  host="$(prompt_target_host 127.0.0.1)"
  port="$(prompt_target_port 22)"
  user="$(read_tty "SSH user [$(infer_ssh_user)]: " "$(infer_ssh_user)")"
  maybe_warn_connectivity "$host" "$port" "SSH"
  payload="$(service_payload ssh "$sid" SSH "$host" "$port" "$user")"
  services_add_json "$payload"
}

add_preset_http() {
  local sid host port payload
  sid="$(prompt_service_id http)"
  host="$(prompt_target_host 127.0.0.1)"
  port="$(prompt_target_port 80)"
  maybe_warn_connectivity "$host" "$port" "HTTP"
  payload="$(service_payload http "$sid" HTTP "$host" "$port")"
  services_add_json "$payload"
}

add_preset_https() {
  local sid host port payload
  sid="$(prompt_service_id https)"
  host="$(prompt_target_host 127.0.0.1)"
  port="$(prompt_target_port 443)"
  maybe_warn_connectivity "$host" "$port" "HTTPS"
  payload="$(service_payload https "$sid" HTTPS "$host" "$port")"
  services_add_json "$payload"
}

add_preset_custom() {
  local sid name host port payload
  sid="$(read_tty "Service ID: " "")"
  name="$(read_tty "Display name [${sid}]: " "$sid")"
  host="$(prompt_target_host 127.0.0.1)"
  port="$(read_tty "Target port: " "")"
  maybe_warn_connectivity "$host" "$port" "TCP"
  payload="$(service_payload custom "$sid" "$name" "$host" "$port")"
  services_add_json "$payload"
}

menu_add_service() {
  local choice
  while true; do
    echo
    echo "Add service"
    echo
    echo "1) SSH"
    echo "2) HTTP"
    echo "3) HTTPS"
    echo "4) Custom TCP"
    echo "5) Back"
    echo
    choice="$(read_tty "Select: " "")"
    case "$choice" in
      1) add_preset_ssh; return 0 ;;
      2) add_preset_http; return 0 ;;
      3) add_preset_https; return 0 ;;
      4) add_preset_custom; return 0 ;;
      5) return 0 ;;
      *) echo "ERROR: select 1-5" >&2 ;;
    esac
  done
}

menu_remove_service() {
  local choice
  if [[ "$(services_count)" == "0" ]]; then
    echo "ERROR: no services to remove" >&2
    return 0
  fi
  echo
  echo "Configured services:"
  echo
  services_list
  echo
  choice="$(read_tty "Remove service number: " "")"
  services_remove_index "$choice"
}

collect_services_interactive() {
  local choice
  while true; do
    echo
    echo "Configured services:"
    echo
    services_list
    echo
    echo "1) Add service"
    echo "2) Remove service"
    echo "3) Install"
    echo "4) Cancel"
    echo
    choice="$(read_tty "Select: " "")"
    case "$choice" in
      1) menu_add_service ;;
      2) menu_remove_service ;;
      3)
        if [[ "$(services_count)" == "0" ]]; then
          echo "ERROR: at least one service must be configured" >&2
          continue
        fi
        return 0
        ;;
      4)
        echo "Cancelled."
        exit 1
        ;;
      *) echo "ERROR: select 1-4" >&2 ;;
    esac
  done
}

collect_services() {
  services_init
  if [[ -n "${FRP_SERVICES_JSON:-}" ]]; then
    services_load_from_env
    if [[ "$(services_count)" == "0" ]]; then
      echo "ERROR: at least one service must be configured" >&2
      exit 1
    fi
    return 0
  fi
  collect_services_interactive
}

print_complete() {
  local server="$1" services_json_file="$2"
  python3 - "$server" "$services_json_file" <<'PY'
import json,sys
from pathlib import Path
server = sys.argv[1]
services = json.loads(Path(sys.argv[2]).read_text(encoding='utf-8'))
print()
print('=========================================')
print(' FRP Installation Complete')
print('=========================================')
print()
print('Published services:')
print()
for item in services:
    name = item.get('name') or item['id']
    preset = item.get('preset') or 'custom'
    remote_port = item.get('remote_port')
    print(name)
    if preset == 'ssh':
        user = item.get('ssh_user') or 'root'
        print(f'  ssh -p {remote_port} {user}@{server}')
    elif preset == 'http':
        print(f'  http://{server}:{remote_port}')
    elif preset == 'https':
        print(f'  https://{server}:{remote_port}')
    else:
        print(f'  {server}:{remote_port}')
    print()
print('Connection information:')
print('cat /etc/frp/access-info.txt')
print()
print('Manage services later without reinstalling:')
print('sudo frp-client')
print()
print('Service status:')
print('sudo frp-client status')
print('sudo systemctl status frpc --no-pager')
print()
print('=========================================')
PY
}

frp_client_main() {
  if [[ ${EUID} -ne 0 && -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    echo "ERROR: run as root, e.g. curl ... | sudo env FRP_ALLOCATOR_URL=... bash" >&2
    exit 1
  fi

  frp_require_allocator_url
  frp_detect_architecture || exit 1

  if [[ -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    frp_detect_platform
    frp_detect_package_manager
    frp_print_detected_linux
    echo
    frp_require_systemd || exit 1
    ensure_dependencies || exit 1
  fi

  cat <<'EOF'

=========================================
 FRP Client Setup
=========================================

EOF

  prompt_secret "Enrollment Code: " FRP_ENROLLMENT_CODE

  if [[ "$FRP_ENROLLMENT_CODE" != *.* ]]; then
    echo "ERROR: invalid enrollment code format" >&2
    exit 1
  fi
  ENROLL_ID="${FRP_ENROLLMENT_CODE%%.*}"
  ENROLL_SECRET="${FRP_ENROLLMENT_CODE#*.}"

  SERVICES_FILE="$(mktemp)"
  ALLOCATED_FILE="$(mktemp)"
  ENROLL_META_FILE="$(mktemp)"
  TMPDIR="$(mktemp -d)"
  trap 'rm -rf "$TMPDIR" "$SERVICES_FILE" "$ALLOCATED_FILE" "$ENROLL_META_FILE"; unset FRP_TOKEN ENROLL_SECRET FRP_ENROLLMENT_CODE TOKEN_CIPHERTEXT' EXIT

  collect_services

  local etc_frp
  etc_frp="$(frp_client_path /etc/frp)"
  mkdir -p "$etc_frp"
  if [[ -n "${FRP_TEST_MACHINE_ID:-}" ]]; then
    MACHINE_ID="$FRP_TEST_MACHINE_ID"
  elif [[ -s /etc/machine-id ]]; then
    MACHINE_ID="$(tr -d '\n' </etc/machine-id)"
  elif [[ -s "${etc_frp}/client-id" ]]; then
    MACHINE_ID="$(tr -d '\n' <"${etc_frp}/client-id")"
  else
    MACHINE_ID="$(openssl rand -hex 16)"
    printf '%s\n' "$MACHINE_ID" >"${etc_frp}/client-id"
    chmod 600 "${etc_frp}/client-id"
  fi

  HOSTNAME_VALUE="${FRP_TEST_HOSTNAME:-$(hostname -s)}"

  echo "Requesting persistent FRP ports ..."
  frp_enroll_services "$ALLOCATOR_URL" "$ENROLL_ID" "$ENROLL_SECRET" \
    "$MACHINE_ID" "$HOSTNAME_VALUE" "$SERVICES_FILE" "$ALLOCATED_FILE" "$ENROLL_META_FILE" \
    || exit 1
  FRP_SERVER="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8"))["frp_server"])' "$ENROLL_META_FILE")"
  FRP_SERVER_PORT="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8"))["frp_server_port"])' "$ENROLL_META_FILE")"
  TOKEN_CIPHERTEXT="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8"))["token_ciphertext"])' "$ENROLL_META_FILE")"
  merge_allocated_services
  FRP_TOKEN="$(frp_decrypt_token "$TOKEN_CIPHERTEXT" "$ENROLL_SECRET")" || exit 1

  if [[ -z "${FRP_ARCH:-}" ]]; then
    frp_detect_architecture || exit 1
  fi

  if [[ "${FRP_SKIP_DOWNLOAD:-}" != "1" ]]; then
    ARCHIVE="$TMPDIR/frp.tar.gz"
    URL="https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/frp_${FRP_VERSION}_linux_${FRP_ARCH}.tar.gz"
    echo "Downloading FRP ${FRP_VERSION} (${FRP_ARCH}) ..."
    curl -fL --retry 3 -o "$ARCHIVE" "$URL"
    printf '%s  %s\n' "$EXPECTED_SHA" "$ARCHIVE" | sha256sum -c -
    tar xzf "$ARCHIVE" -C "$TMPDIR"
    install -m 0755 "$TMPDIR/frp_${FRP_VERSION}_linux_${FRP_ARCH}/frpc" /usr/local/bin/frpc
  fi

  HOST_SAFE="$(printf '%s' "$HOSTNAME_VALUE" | tr -cs 'A-Za-z0-9._-' '-')"
  HOST_ID="${HOST_SAFE}-${MACHINE_ID:0:8}"
  FRPC_TOML="$(frp_client_path /etc/frp/frpc.toml)"
  ACCESS_INFO="$(frp_client_path /etc/frp/access-info.txt)"
  mkdir -p "$(dirname "$FRPC_TOML")"
  render_frpc_toml "$FRPC_TOML" "$FRP_SERVER" "$FRP_SERVER_PORT" "$FRP_TOKEN" "$HOST_ID" "$SERVICES_FILE"
  frp_client_verify_config "$FRPC_TOML" || exit 1

  if [[ "${FRP_SKIP_SYSTEMD:-}" != "1" && -z "${FRP_CLIENT_TEST_ROOT:-}" ]]; then
    cat >/etc/systemd/system/frpc.service <<'EOF2'
[Unit]
Description=FRP Client
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/frpc -c /etc/frp/frpc.toml
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF2
    systemctl daemon-reload
    systemctl enable frpc >/dev/null
    systemctl restart frpc

    mapfile -t PROXY_NAMES < <(proxy_names_from_services "$HOST_ID")
    if ! wait_for_proxies "${PROXY_NAMES[@]}"; then
      echo "ERROR: frpc did not register every requested proxy successfully" >&2
      journalctl -u frpc -n 80 --no-pager >&2 || true
      exit 1
    fi
  fi

  render_access_info "$ACCESS_INFO" "$FRP_SERVER" "$SERVICES_FILE"
  frp_write_client_state "$(frp_client_state_path)" "$ALLOCATOR_URL" "$FRP_SERVER" \
    "$FRP_SERVER_PORT" "$HOSTNAME_VALUE" "$MACHINE_ID" "$HOST_ID" "$SERVICES_FILE"
  frp_state_has_secrets "$(frp_client_state_path)" || {
    echo "ERROR: client-state.json must not contain secrets" >&2
    exit 1
  }

  mkdir -p "$(frp_client_lib_dir)" "$(frp_client_path /usr/local/bin)"
  if [[ -f "${_FRP_INSTALL_CLIENT_DIR}/lib/frp-client-common.sh" ]]; then
    install -m 0644 "${_FRP_INSTALL_CLIENT_DIR}/lib/frp-client-common.sh" \
      "$(frp_client_lib_dir)/frp-client-common.sh"
  fi
  if [[ -f "${_FRP_INSTALL_CLIENT_DIR}/tools/frp-client" ]]; then
    install -m 0755 "${_FRP_INSTALL_CLIENT_DIR}/tools/frp-client" \
      "$(frp_client_path /usr/local/bin/frp-client)"
  fi

  print_complete "$FRP_SERVER" "$SERVICES_FILE"
}

if [[ "${FRP_CLIENT_SOURCED:-}" != "1" ]]; then
  frp_client_main "$@"
fi
